### ISSUE TITLE
Operator istore - int[]

### ISSUE THREAD

**Issue by ArturFormella** [adjust/istore#72]
Hello!
Could you add a new subtract operator?

istore - integer[] 

Description:
subtract keys from istore 	
Example:
'1=>4,2=>5'::istore - '{2,4}'::integer[] 
Result:
"1"=>"4"

**Comment by chochkov** [comment]
@ArturFormella the functionality already exists as a function:

```
nikola@[local] nikola # \dx istore
            List of installed extensions
  Name  | Version | Schema |       Description
--------+---------+--------+-------------------------
 istore | 0.1.6   | public | an integer based hstore
(1 row)

nikola@[local] nikola # select delete('1=>0, 2=>0, 3=>0'::istore, '{2,3}'::integer[]);
  delete
----------
 "1"=>"0"
(1 row)
```

**Comment by ArturFormella** [comment]
Oh, thank you for pointing this out!

**Comment by rapimo** [comment]
do we finally want this as operator? What are the benefits having an operator over a function?

**Comment by einhverfr** [comment]
On further thought I think a function is clearer here than an operator (which is just semantic sugar around a function anyway).  A subtraction operator might not be sufficiently clear in that case especially if you think of istore as a sparse array.
