### ISSUE TITLE
Introduce functions to control the upper and lower boundaries of the values in istore 

### ISSUE THREAD

**Issue by alexeyklyukin** [adjust/istore#86]
Namely, 
`in_range(istore, lower, upper)` to return true iff all values in the map are in the given range;
`less_than(istore, upper)` - returns true iff all values are lower than the given one.
`greater_than(istore, lower)` - true iff all values are greater the given one.
also, less_or_equal version of all.

In addition,
`floor(istore, floor_value)`  to set all values lower than the floor_value to that value
`ceiling(istore, ceiling_value)` to set all values higher than the ceiling_value to that value.  

That would be kind of coalesce values, together with the functions to check if we need to coalesce (for cases when there are values in the cohorts we need to correct, i.e. negatives).

**Comment by ildus** [comment]
should we close this issue?

**Comment by alexeyklyukin** [comment]
I think we should.
